// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_school_API.Data;

namespace project_school_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191215194358_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("project_school_API.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DataNasc");

                    b.Property<string>("Nome");

                    b.Property<int>("ProfessorId");

                    b.Property<string>("Sobrenome");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNasc = "16/10/2000",
                            Nome = "Maria",
                            ProfessorId = 1,
                            Sobrenome = "Alborraz"
                        },
                        new
                        {
                            Id = 2,
                            DataNasc = "20/11/2015",
                            Nome = "João",
                            ProfessorId = 2,
                            Sobrenome = "Canela"
                        },
                        new
                        {
                            Id = 3,
                            DataNasc = "01/01/2001",
                            Nome = "Alex",
                            ProfessorId = 2,
                            Sobrenome = "Ferreira"
                        });
                });

            modelBuilder.Entity("project_school_API.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Vicente"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Paula"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Luna"
                        });
                });

            modelBuilder.Entity("project_school_API.Models.Aluno", b =>
                {
                    b.HasOne("project_school_API.Models.Professor", "Professor")
                        .WithMany("Alunos")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
